---
# tasks file for apache
- name : instal apache
  ansible.builtin.dnf:
     name: httpd
     state: present

- name : start the apache
  ansible.builtin.service:
      name: httpd
      state: started

- name : change welcome page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html

- name : changing the port number
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart apache
#
